// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh3V9wHDHSrvmFtKzUTz72glJgSb5uOD0',
    appId: '1:460244117327:web:5d32055ff21f3161f9473a',
    messagingSenderId: '460244117327',
    projectId: 'groceryapp2-28844',
    authDomain: 'groceryapp2-28844.firebaseapp.com',
    storageBucket: 'groceryapp2-28844.firebasestorage.app',
    measurementId: 'G-HMR466M3XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChV_ihdwMrKsTr9xWBwN2BHM5pPHaIsA4',
    appId: '1:460244117327:android:dcf72248c6471d67f9473a',
    messagingSenderId: '460244117327',
    projectId: 'groceryapp2-28844',
    storageBucket: 'groceryapp2-28844.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT4__0ywaU9TuQoXNb01fqIje784FGNoU',
    appId: '1:460244117327:ios:c0a117aa5d5b5a13f9473a',
    messagingSenderId: '460244117327',
    projectId: 'groceryapp2-28844',
    storageBucket: 'groceryapp2-28844.firebasestorage.app',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT4__0ywaU9TuQoXNb01fqIje784FGNoU',
    appId: '1:460244117327:ios:c0a117aa5d5b5a13f9473a',
    messagingSenderId: '460244117327',
    projectId: 'groceryapp2-28844',
    storageBucket: 'groceryapp2-28844.firebasestorage.app',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh3V9wHDHSrvmFtKzUTz72glJgSb5uOD0',
    appId: '1:460244117327:web:75a4d0c4af4cbca8f9473a',
    messagingSenderId: '460244117327',
    projectId: 'groceryapp2-28844',
    authDomain: 'groceryapp2-28844.firebaseapp.com',
    storageBucket: 'groceryapp2-28844.firebasestorage.app',
    measurementId: 'G-R3W7DC92C3',
  );
}
